### PR TITLE
Initial update to 2.0 + translation sheet updated

### LINKED ISSUE #5: Translations for new Items are not pulled, because the sheet has not been Updated
This is a spreadsheet that still gets updated and should be used:
https://docs.google.com/spreadsheets/d/1MMbsvDfu59OY9YBEAfHhFJ6O8vRTllNFgMrX7RBZuyI

### LINKED ISSUE #6: Update to 2.0
Is in program an update to 2.0 version?

### PR DESCRIPTION
**Pull request by papjul**
Fixes #5
Fixes #6

Updated to 2.0. Uses new translation source (that is still updated).

Breaking changes:
- Translation attributes are no longer english, french, etc, but uSen, eUfr, etc (due to change of translation sheet source)
- Art is renamed Artwork in the sheet
- Tools is renamed Tools/Goods in the sheet

Remaining things to do:
- It initially fails when parsing Tools/Goods sheet because of the "/" character, saying the directory doesn't exist. To workaround, I created a subfolder Tools, let it parse Goods.json in it, and then move it to the top directory as Tools.json. This should be handled by the code.
- USen and other translation attributes are renamed uSen, but it would be better to keep USen.
- Take into account new tabs (mainly HHA expansion).
- Take into account new translation tabs.
- Check if there are new fields in the 2.0 sheet.
- Update TypeScript models
- Update documentation
- etc

Yes, many things left to do, but at least, we have updated working json :)

### CODE REVIEW

**Comment by papjul** [comment]
It appears some translations are mismatched, I need to investigate why.

**Comment by Norviah** [comment]
myb for the late message, have ya tried using the build script? but ill look into this in the next upcoming days, thank ya for your help

**Comment by papjul** [comment]
You mean the translation issue? I fixed it in an additional commit, it was due to a strict comparison while IDs were sometimes string, sometimes number ;)

**Comment by Norviah** [comment]
naah i mean in package.json, i use a build script to generate the module and im wondering if u have used it to see if it is successful, but ignore it cause ill look at it rn

**Comment by papjul** [comment]
I only used `npm run build:src && npm run start` as per the documentation ;)

**Comment by Norviah** [comment]
i see, i wasnt that specific but running it is what i meant, so if its successful for you then it should be good, but ill run it on my end just in case

**Comment by papjul** [comment]
> i see, i wasnt that specific but running it is what i meant, so if its successful for you then it should be good, but ill run it on my end just in case

Yes, but I made changes to the src/ directory, maybe you should have a look at it before modifying master a second time ;)

https://github.com/papjul/animal-crossing/tree/update_2-0/src/util

You also need to make the workaround for Tools/Goods (see first post). It's probably something to be fixed in the `sheets` dependency ;)

**Comment by Norviah** [comment]
thank ya, and myb as it seems i overwritten your fork of the repo somehow?? i thought only pushes would go to this pull request :/ but i fixed the issue of the path thing when saving in `sheets` and everything else looks good, im going to run it a few more times to make sure and ill push the changes. thank u again for your help

**Comment by papjul** [comment]
No worries, the pull request is linked to my branch and I allowed you to make changes in case you needed to ;)

**Pull request merged**
